[tool.poetry]
name = "oc_meta"
version = "1.1.2"
description = "OpenCitations Meta contains bibliographic metadata associated with the documents involved in the citations stored in the OpenCitations infrastructure. The OpenCitations Meta Software performs two main actions: a data curation of the provided CSV files and the generation of new RDF files compliant with the OpenCitations Data Model."
authors = ["Arcangelo Massari <arcangelomas@gmail.com>", "Fabio Mariani", "Simone Persiani <iosonopersia@gmail.com>"]
license = "ISC License"

[tool.poetry.dependencies]
python = "^3.7"
argparse = "^1.4.0"
lxml = "4.9.1"
beautifulsoup4 = "^4.11.1"
oc-ocdm = "^7.0.0"
python-dateutil = "^2.8.2"
PyYAML = "^6.0"
requests = "^2.27.1"
rdflib = "^6.1.1"
SPARQLWrapper = "1.8.5"
time-agnostic-library = "^3.1.0"
tqdm = "^4.64.0"
filelock = "^3.6.0"
psutil = "^5.9.0"
Pebble = "^4.6.3"
ramose = "^1.0.6"

[tool.poetry.dev-dependencies]
wget = "^3.2"
requests-cache = "^0.9.4"
ramose = "^1.0.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
test = 'test.run_all_tests:main'
